module.exports = {
  SUCCESS_CODE: 200,
  ACCEPTED_CODE: 202,
  UNAUTHORIZED_CODE: 401,
  FORBIDDEN_CODE: 403,
  BAD_REQUEST_CODE: 400,
  SERVER_ERROR_CODE: 500,
  LIMIT_PER_PAGE:10,
  SERVER_ERROR: 'Internal Server Error',
  INVALID_CREDENTIALS: 'Password is invalid',
  ACCOUNT_ALREADY_REGISTERED: 'Account is already registerd',
  LOGIN_SUCCESS: 'Login Successfully',
  ACCOUNT_NOT_EXISTS: 'Account does not exists',
  AUTHORIZATION_NOT_SENT: 'Authorization required',
  TOKEN_EXPIRED: 'Token is expired',
  INVALID_TOKEN_EXPIRED: 'Invalid token or token is expired',
  UNAUTHORIZED_ACCESS: 'Unauthorized Access',
  USER_CREATED: 'User is created',
  USER_FOUND: 'User is found',
  USER_NOT_FOUND: 'No User exists',
  USER_UPDATED: 'User is updated',
  USER_NOT_UPDATED: 'User is not updated',
  USER_DELETED: 'User is deleted',
  USER_NOT_DELETED: 'User is not deleted',
  ORGANIZATION_NOT_EXISTS:'Organization does not exists',
  USER_LIST_SUCCESS: 'User listed successfully',
};
